# ---------------
# Deployment
#----------------
apiVersion: extensions/v1beta1
metadata:
  name: kubernetes-sample-api
  namespace: app
kind: Deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-sample-api
    spec:
      containers:
        - name: kubernetes-sample-api
          image: chrismckenna555/kubernetes_sample_api
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      restartPolicy: Always
---
# ---------------
# Service
#----------------
apiVersion: v1
metadata:
  name: kubernetes-sample-api
  namespace: app
kind: Service
spec:
  selector:
    app: kubernetes-sample-api
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  type: NodePort